version: '2'
services:
  notebooks_sandbox:
    image: rybval/notebooks_sandbox
    build: ./
    volumes:
      - "${NOTEBOOKS_DIR}:/jupyter"
    ports:
      - "8888:8888"
    restart: unless-stopped
